"""Registry metadata for the Cenas in-app assistant.

The route layer binds these metadata entries to local handler callables. Keeping
the metadata here lets catalog generation and deterministic routing grow without
adding another hand-written block to ``assistant_routes.py``.
"""
from __future__ import annotations

from copy import deepcopy
from typing import Any, Iterable


BUILTIN_TOOL_REGISTRY: list[dict[str, Any]] = [
    {
        "tool_id": "assistant.general_help",
        "label": "General app help",
        "description": "Answer general navigation, workflow, and policy-style questions without private operational data.",
        "required_permissions": ["ai.ask_claude_personal"],
        "session_types": ["partner", "staff", "employee", "driver"],
        "store_scope": "none",
        "data_class": "general",
        "read_write_class": "read_only",
        "status": "active",
        "priority": 900,
    },
    {
        "tool_id": "employee.my_profile",
        "label": "Own employee profile",
        "description": "Future read-only personal profile answers scoped to the current employee.",
        "required_permissions": ["ai.ask_claude_personal"],
        "session_types": ["employee", "staff"],
        "store_scope": "own_profile",
        "data_class": "personal_profile",
        "read_write_class": "read_only",
        "status": "review_gated",
        "priority": 900,
    },
    {
        "tool_id": "orders.store_summary",
        "label": "Store order summary",
        "description": "Store-scoped order and catering summaries from approved marts.",
        "required_permissions": ["ai.ask_claude", "orders.view"],
        "session_types": ["partner", "staff"],
        "store_scope": "current_user_store_scope",
        "data_class": "operations",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": "orders_store_summary",
        "matcher": "orders_store_summary",
        "formatter": "orders_store_summary",
        "priority": 300,
    },
    {
        "tool_id": "drivers.store_summary",
        "label": "Driver summary",
        "description": "Driver performance and delivery summaries from CK driver marts.",
        "required_permissions": ["ai.ask_claude", "drivers.view_roster"],
        "session_types": ["partner", "staff"],
        "store_scope": "current_user_store_scope",
        "data_class": "driver_operations",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": "drivers_store_summary",
        "matcher": "drivers_store_summary",
        "formatter": "drivers_store_summary",
        "priority": 320,
    },
    {
        "tool_id": "labor.store_aggregate",
        "label": "Labor aggregate",
        "description": "Aggregate-only labor answers from approved employee marts.",
        "required_permissions": ["ai.ask_claude", "labor.view_store_summary"],
        "session_types": ["partner", "staff"],
        "store_scope": "current_user_store_scope",
        "data_class": "labor_aggregate",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": "labor_store_aggregate",
        "matcher": "labor_store_aggregate",
        "formatter": "labor_store_aggregate",
        "priority": 330,
    },
    {
        "tool_id": "toast.sales_summary",
        "label": "Toast sales summary",
        "description": "Read-only Toast Analytics sales, order, labor, and menu aggregates for an approved period.",
        "required_permissions": ["ai.ask_claude", "sales.view_today"],
        "session_types": ["partner", "staff"],
        "store_scope": "current_user_store_scope",
        "data_class": "sales_aggregate",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": "toast_sales_summary",
        "matcher": "toast_sales_summary",
        "formatter": "toast_sales_summary",
        "priority": 100,
    },
    {
        "tool_id": "toast.table_activity",
        "label": "Toast table activity",
        "description": "Read-only latest in-store Toast table open activity with sanitized table labels and timestamps.",
        "required_permissions": ["ai.ask_claude", "sales.view_today"],
        "session_types": ["partner", "staff"],
        "store_scope": "current_user_store_scope",
        "data_class": "table_activity",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": "toast_table_activity",
        "matcher": "toast_table_activity",
        "formatter": "toast_table_activity",
        "priority": 80,
    },
    {
        "tool_id": "toast.webhook_activity",
        "label": "Toast webhook activity",
        "description": "Read-only live Toast webhook/order/check/item/payment activity from the CK central webhook database.",
        "required_permissions": ["ai.ask_claude", "sales.view_today"],
        "session_types": ["partner", "staff"],
        "store_scope": "current_user_store_scope",
        "data_class": "toast_webhook_activity",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": "toast_webhook_activity",
        "matcher": "toast_webhook_activity",
        "formatter": "toast_webhook_activity",
        "priority": 70,
    },
    {
        "tool_id": "toast.employee_profiles",
        "label": "Toast employee profiles",
        "description": "Read-only employee-specific Toast facts from CK's per-employee Toast profile databases.",
        "required_permissions": ["ai.ask_claude", "labor.view_store_summary"],
        "session_types": ["partner", "staff"],
        "store_scope": "partner_all_stores",
        "data_class": "toast_employee_profiles",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": "toast_employee_profiles",
        "matcher": "toast_employee_profiles",
        "formatter": "toast_employee_profiles",
        "priority": 60,
    },
]


def iter_builtin_tool_registrations() -> Iterable[dict[str, Any]]:
    for entry in BUILTIN_TOOL_REGISTRY:
        yield deepcopy(entry)
