"""Registry metadata for the Cenas in-app assistant.

The route layer binds these metadata entries to local handler callables. Keeping
the metadata here lets catalog generation and deterministic routing grow without
adding another hand-written block to ``assistant_routes.py``.
"""
from __future__ import annotations

from copy import deepcopy
from typing import Any, Iterable


BUILTIN_TOOL_REGISTRY: list[dict[str, Any]] = [
    {
        "tool_id": "assistant.general_help",
        "label": "General app help",
        "description": "Answer general navigation, workflow, and policy-style questions without private operational data.",
        "required_permissions": ["ai.ask_claude_personal"],
        "session_types": ["partner", "staff", "employee", "driver"],
        "store_scope": "none",
        "data_class": "general",
        "read_write_class": "read_only",
        "status": "active",
        "priority": 900,
    },
    {
        "tool_id": "employee.my_profile",
        "label": "Own employee profile",
        "description": "Future read-only personal profile answers scoped to the current employee.",
        "required_permissions": ["ai.ask_claude_personal"],
        "session_types": ["employee", "staff"],
        "store_scope": "own_profile",
        "data_class": "personal_profile",
        "read_write_class": "read_only",
        "status": "review_gated",
        "priority": 900,
    },
    {
        "tool_id": "orders.store_summary",
        "label": "Store order summary",
        "description": "Store-scoped order and catering summaries from approved marts.",
        "required_permissions": ["ai.ask_claude", "orders.view"],
        "session_types": ["partner", "staff"],
        "store_scope": "current_user_store_scope",
        "data_class": "operations",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": "orders_store_summary",
        "matcher": "orders_store_summary",
        "formatter": "orders_store_summary",
        "priority": 300,
    },
    {
        "tool_id": "drivers.store_summary",
        "label": "Driver summary",
        "description": "Driver performance and delivery summaries from CK driver marts.",
        "required_permissions": ["ai.ask_claude", "drivers.view_roster"],
        "session_types": ["partner", "staff"],
        "store_scope": "current_user_store_scope",
        "data_class": "driver_operations",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": "drivers_store_summary",
        "matcher": "drivers_store_summary",
        "formatter": "drivers_store_summary",
        "priority": 320,
    },
    {
        "tool_id": "labor.store_aggregate",
        "label": "Labor aggregate",
        "description": "Aggregate-only labor answers from approved employee marts.",
        "required_permissions": ["ai.ask_claude", "labor.view_store_summary"],
        "session_types": ["partner", "staff"],
        "store_scope": "current_user_store_scope",
        "data_class": "labor_aggregate",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": "labor_store_aggregate",
        "matcher": "labor_store_aggregate",
        "formatter": "labor_store_aggregate",
        "priority": 330,
    },
    {
        "tool_id": "toast.sales_summary",
        "label": "Toast sales summary",
        "description": "Read-only Toast Analytics sales, order, labor, and menu aggregates for an approved period.",
        "required_permissions": ["ai.ask_claude", "sales.view_today"],
        "session_types": ["partner", "staff"],
        "store_scope": "current_user_store_scope",
        "data_class": "sales_aggregate",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": "toast_sales_summary",
        "matcher": "toast_sales_summary",
        "formatter": "toast_sales_summary",
        "priority": 100,
    },
    {
        "tool_id": "toast.table_activity",
        "label": "Toast table activity",
        "description": "Read-only latest in-store Toast table open activity with sanitized table labels and timestamps.",
        "required_permissions": ["ai.ask_claude", "sales.view_today"],
        "session_types": ["partner", "staff"],
        "store_scope": "current_user_store_scope",
        "data_class": "table_activity",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": "toast_table_activity",
        "matcher": "toast_table_activity",
        "formatter": "toast_table_activity",
        "priority": 80,
    },
    {
        "tool_id": "toast.webhook_activity",
        "label": "Toast webhook activity",
        "description": "Read-only live Toast webhook/order/check/item/payment activity from the CK central webhook database.",
        "required_permissions": ["ai.ask_claude", "sales.view_today"],
        "session_types": ["partner", "staff"],
        "store_scope": "current_user_store_scope",
        "data_class": "toast_webhook_activity",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": "toast_webhook_activity",
        "matcher": "toast_webhook_activity",
        "formatter": "toast_webhook_activity",
        "priority": 70,
    },
    {
        "tool_id": "toast.employee_profiles",
        "label": "Toast employee profiles",
        "description": "Read-only employee-specific Toast facts from CK's per-employee Toast profile databases.",
        "required_permissions": ["ai.ask_claude", "labor.view_store_summary"],
        "session_types": ["partner", "staff"],
        "store_scope": "partner_all_stores",
        "data_class": "toast_employee_profiles",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": "toast_employee_profiles",
        "matcher": "toast_employee_profiles",
        "formatter": "toast_employee_profiles",
        "priority": 60,
    },
]


def _orders_read_tool(
    tool_id: str,
    label: str,
    description: str,
    handler: str,
    matcher: str,
    priority: int,
) -> dict[str, Any]:
    return {
        "tool_id": tool_id,
        "label": label,
        "description": description,
        "required_permissions": ["ai.ask_claude", "orders.view"],
        "session_types": ["partner", "staff"],
        "store_scope": "current_user_store_scope",
        "data_class": "operations",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": handler,
        "matcher": matcher,
        "formatter": handler,
        "priority": priority,
    }


BUILTIN_TOOL_REGISTRY.extend([
    _orders_read_tool(
        "orders.catering_needs_driver",
        "Catering needs driver",
        "Store-scoped catering orders that still need driver attention.",
        "orders_catering_needs_driver",
        "orders_catering_needs_driver",
        205,
    ),
    _orders_read_tool(
        "orders.catering_live_tracking",
        "Catering live tracking",
        "Store-scoped catering orders with live tracking UUIDs and active tracking status.",
        "orders_catering_live_tracking",
        "orders_catering_live_tracking",
        206,
    ),
    _orders_read_tool(
        "orders.catering_tracking_missing",
        "Catering missing tracking",
        "Store-scoped active catering orders missing live tracking UUIDs.",
        "orders_catering_tracking_missing",
        "orders_catering_tracking_missing",
        207,
    ),
    _orders_read_tool(
        "orders.catering_uuid_status",
        "Catering tracking UUID status",
        "Aggregate tracking UUID and status coverage for visible catering orders.",
        "orders_catering_uuid_status",
        "orders_catering_uuid_status",
        208,
    ),
    _orders_read_tool(
        "orders.catering_late_risk",
        "Catering late risk",
        "Store-scoped same-day catering orders that appear overdue or late risk.",
        "orders_catering_late_risk",
        "orders_catering_late_risk",
        209,
    ),
    _orders_read_tool(
        "orders.catering_today",
        "Catering today",
        "Store-scoped list and count of today's catering orders.",
        "orders_catering_today",
        "orders_catering_today",
        210,
    ),
    _orders_read_tool(
        "orders.catering_tomorrow",
        "Catering tomorrow",
        "Store-scoped list and count of tomorrow's catering orders.",
        "orders_catering_tomorrow",
        "orders_catering_tomorrow",
        211,
    ),
    _orders_read_tool(
        "orders.catering_next_30_days",
        "Catering next 30 days",
        "Store-scoped catering order counts and samples for the next 30 days.",
        "orders_catering_next_30_days",
        "orders_catering_next_30_days",
        212,
    ),
    _orders_read_tool(
        "orders.catering_week",
        "Catering week",
        "Store-scoped catering order counts and samples for the next 7 days.",
        "orders_catering_week",
        "orders_catering_week",
        213,
    ),
    _orders_read_tool(
        "orders.catering_by_store",
        "Catering by store",
        "Store split for visible catering orders.",
        "orders_catering_by_store",
        "orders_catering_by_store",
        214,
    ),
    _orders_read_tool(
        "orders.catering_by_status",
        "Catering by status",
        "Status split for visible catering orders.",
        "orders_catering_by_status",
        "orders_catering_by_status",
        215,
    ),
    _orders_read_tool(
        "orders.catering_item_mix",
        "Catering item mix",
        "Sanitized item mix and top item quantities across visible catering orders.",
        "orders_catering_item_mix",
        "orders_catering_item_mix",
        216,
    ),
    _orders_read_tool(
        "orders.catering_order_items_safe",
        "Catering order items",
        "Sanitized item list for one visible catering order without contact details.",
        "orders_catering_order_items_safe",
        "orders_catering_order_items_safe",
        203,
    ),
    _orders_read_tool(
        "orders.catering_order_lookup",
        "Catering order lookup",
        "Sanitized details for one visible catering order without customer contact data.",
        "orders_catering_order_lookup",
        "orders_catering_order_lookup",
        204,
    ),
    _orders_read_tool(
        "orders.catering_driver_assignment_summary",
        "Catering driver assignment summary",
        "Aggregate status of driver assignment jobs for visible catering orders.",
        "orders_catering_driver_assignment_summary",
        "orders_catering_driver_assignment_summary",
        219,
    ),
    _orders_read_tool(
        "orders.catering_fees_summary",
        "Catering fees summary",
        "Aggregate fee, tip, and PDF-extracted fee totals for visible catering orders.",
        "orders_catering_fees_summary",
        "orders_catering_fees_summary",
        220,
    ),
    _orders_read_tool(
        "orders.catering_payout_safe_summary",
        "Catering payout summary",
        "Aggregate-only payout and mileage totals for visible catering orders.",
        "orders_catering_payout_safe_summary",
        "orders_catering_payout_safe_summary",
        221,
    ),
    _orders_read_tool(
        "orders.catering_pdf_status",
        "Catering PDF status",
        "Aggregate PDF processing and extraction status for visible catering orders.",
        "orders_catering_pdf_status",
        "orders_catering_pdf_status",
        222,
    ),
    _orders_read_tool(
        "orders.catering_returning_customers_aggregate",
        "Catering returning customers",
        "Aggregate repeat-customer counts without exposing customer names or contact data.",
        "orders_catering_returning_customers_aggregate",
        "orders_catering_returning_customers_aggregate",
        223,
    ),
    _orders_read_tool(
        "orders.catering_count",
        "Catering count",
        "Store-scoped catering counts across current, daily, weekly, and 30-day windows.",
        "orders_catering_count",
        "orders_catering_count",
        245,
    ),
    _orders_read_tool(
        "orders.in_house_quote_lookup",
        "In-house quote lookup",
        "Sanitized details for one in-house catering quote without contact data.",
        "orders_in_house_quote_lookup",
        "orders_in_house_quote_lookup",
        201,
    ),
    _orders_read_tool(
        "orders.in_house_quotes_summary",
        "In-house quotes summary",
        "Store-scoped in-house catering quote counts, status split, and sanitized recent list.",
        "orders_in_house_quotes_summary",
        "orders_in_house_quotes_summary",
        202,
    ),
])


def _schedule_read_tool(
    tool_id: str,
    label: str,
    description: str,
    handler: str,
    matcher: str,
    priority: int,
) -> dict[str, Any]:
    return {
        "tool_id": tool_id,
        "label": label,
        "description": description,
        "required_permissions": ["ai.ask_claude", "schedule.view"],
        "session_types": ["partner", "staff"],
        "store_scope": "current_user_store_scope",
        "data_class": "schedule_operations",
        "read_write_class": "read_only",
        "status": "review_gated",
        "operator_enabled": True,
        "handler": handler,
        "matcher": matcher,
        "formatter": handler,
        "priority": priority,
    }


BUILTIN_TOOL_REGISTRY.extend([
    _schedule_read_tool(
        "schedule.alarm_pending_summary",
        "Schedule pending alarms",
        "Store-scoped pending schedule reminder counts from internal Schedules V2.",
        "schedule_alarm_pending_summary",
        "schedule_alarm_pending_summary",
        225,
    ),
    _schedule_read_tool(
        "schedule.availability_conflicts",
        "Schedule availability conflicts",
        "Store-scoped soft availability and unavailability conflicts for upcoming Schedules V2 shifts.",
        "schedule_availability_conflicts",
        "schedule_availability_conflicts",
        226,
    ),
    _schedule_read_tool(
        "schedule.open_shifts",
        "Open schedule shifts",
        "Store-scoped open and unassigned shifts from internal Schedules V2.",
        "schedule_open_shifts",
        "schedule_open_shifts",
        227,
    ),
    _schedule_read_tool(
        "schedule.shift_acceptance_summary",
        "Shift acceptance summary",
        "Store-scoped accepted, declined, and pending shift-acceptance counts from internal Schedules V2.",
        "schedule_shift_acceptance_summary",
        "schedule_shift_acceptance_summary",
        228,
    ),
    _schedule_read_tool(
        "schedule.shift_offer_summary",
        "Shift offer summary",
        "Store-scoped shift-offer marketplace summary from internal Schedules V2.",
        "schedule_shift_offer_summary",
        "schedule_shift_offer_summary",
        229,
    ),
    _schedule_read_tool(
        "schedule.shift_swap_summary",
        "Shift swap summary",
        "Store-scoped shift-swap marketplace summary from internal Schedules V2.",
        "schedule_shift_swap_summary",
        "schedule_shift_swap_summary",
        230,
    ),
    _schedule_read_tool(
        "schedule.store_today",
        "Today's schedule",
        "Store-scoped today's shift summary from internal Schedules V2.",
        "schedule_store_today",
        "schedule_store_today",
        231,
    ),
    _schedule_read_tool(
        "schedule.store_week",
        "This week's schedule",
        "Store-scoped current-week schedule summary from internal Schedules V2.",
        "schedule_store_week",
        "schedule_store_week",
        232,
    ),
    _schedule_read_tool(
        "schedule.time_off_pending",
        "Pending time off",
        "Store-scoped pending time-off request counts from internal Schedules V2.",
        "schedule_time_off_pending",
        "schedule_time_off_pending",
        233,
    ),
    _schedule_read_tool(
        "schedule.unavailability_blocks",
        "Unavailability blocks",
        "Store-scoped upcoming unavailability blocks from internal Schedules V2.",
        "schedule_unavailability_blocks",
        "schedule_unavailability_blocks",
        234,
    ),
    _schedule_read_tool(
        "schedule.view",
        "Schedule view",
        "Generic store-scoped current schedule summary from internal Schedules V2.",
        "schedule_view",
        "schedule_view",
        246,
    ),
])


TOOL_ALIAS_MAP: dict[str, str] = {
    "catering.assign_driver": "orders.assign_driver",
    "catering.reassign_store": "orders.reassign_store",
    "catering.unassign": "orders.unassign_driver",
    "catering.view_drivers": "drivers.roster_summary",
    "driver.approve_mileage": "drivers.approve_mileage",
    "driver.view_all_queue": "drivers.active_delivery_queue",
    "driver.view_earnings": "drivers.earnings_own",
    "driver.view_own_queue": "drivers.active_delivery_queue",
    "emp.add": "employee.add",
    "emp.archive": "employee.deactivate",
    "emp.edit_info": "employee.edit_profile",
    "emp.reset_passcode": "employee.reset_passcode",
    "emp.view_directory": "employees.store_directory",
    "emp.view_perf": "employees.performance_safe_summary",
    "fin.approve_expense": "finance.approve_expense",
    "fin.view_ap": "finance.ap_summary",
    "fin.view_deposits": "finance.deposit_summary",
    "fin.view_instant_deposit": "finance.instant_deposit_status",
    "fin.view_payroll": "finance.payroll_setup_summary",
    "fin.view_pnl": "finance.pnl_summary",
    "fin.view_tips": "finance.tip_pool_summary",
    "incident.create": "manager.create_incident",
    "incident.edit": "manager.edit_incident",
    "incident.view": "manager.incident_summary",
    "kitchen.fresh_edit": "kitchen.update_fresh_food",
    "kitchen.prep_edit": "kitchen.update_prep_item",
    "legal.compliance_cal": "legal.compliance_calendar",
    "legal.upload_docs": "legal.upload_document",
    "legal.view_docs": "legal.document_search",
    "legal.view_insurance": "legal.insurance_summary",
    "legal.view_licenses": "legal.license_summary",
    "maint.close": "maintenance.close_request",
    "maint.submit": "maintenance.create_request",
    "maint.view": "manager.maintenance_summary",
    "manager_log.write": "manager.create_daily_log",
    "perms.assign": "permissions.assign_role",
    "perms.assign_role": "permissions.assign_role",
    "perms.create_role": "permissions.create_role_template",
    "perms.edit_role": "permissions.edit_role_template",
    "perms.override": "permissions.override_user_permission",
    "perms.view": "permissions.permission_catalog",
    "reports.benchmarks": "reports.benchmark_summary",
    "reports.catering": "reports.catering_summary",
    "reports.catering_item_mix": "orders.catering_item_mix",
    "reports.cross_store": "reports.cross_store_summary",
    "reports.forecasts": "reports.forecast_summary",
    "reports.labor": "reports.labor_summary",
    "reports.marketing": "reports.marketing_summary",
    "reports.sales": "reports.sales_summary",
    "team.notify": "manager.send_team_notification",
    "timeoff.approve": "schedule.approve_time_off",
    "toast_live_tables": "toast.table_activity",
}


def canonical_tool_id(tool_id: str) -> str:
    current = str(tool_id or "").strip()
    seen: set[str] = set()
    while current in TOOL_ALIAS_MAP and current not in seen:
        seen.add(current)
        current = TOOL_ALIAS_MAP[current]
    return current


def iter_tool_aliases() -> Iterable[tuple[str, str]]:
    for alias, canonical in sorted(TOOL_ALIAS_MAP.items()):
        yield alias, canonical


def iter_builtin_tool_registrations() -> Iterable[dict[str, Any]]:
    for entry in BUILTIN_TOOL_REGISTRY:
        yield deepcopy(entry)
